import type { YtdTotals } from "@/server/hmrc/payroll";

function gbp(pence: number) {
  return new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
  }).format(pence / 100);
}

function esc(s: string) {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function documentShell(title: string, body: string) {
  return `<!DOCTYPE html>
<html lang="en-GB">
<head>
  <meta charset="utf-8" />
  <title>${esc(title)}</title>
  <style>
    body { font-family: Georgia, "Times New Roman", serif; color: #111; margin: 0; padding: 24px; background: #f6f4ef; }
    .sheet { max-width: 800px; margin: 0 auto; background: #fff; border: 1px solid #d4d0c8; padding: 28px 32px; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    .sub { color: #555; font-size: 13px; margin-bottom: 20px; }
    h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 0.04em; margin: 22px 0 8px; border-bottom: 1px solid #ddd; padding-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 14px; }
    th, td { text-align: left; padding: 6px 4px; vertical-align: top; }
    th { width: 42%; color: #444; font-weight: 600; }
    .num { text-align: right; font-variant-numeric: tabular-nums; }
    .note { margin-top: 20px; font-size: 12px; color: #555; line-height: 1.45; }
    .actions { margin: 16px auto; max-width: 800px; }
    .actions button { font: inherit; padding: 8px 14px; cursor: pointer; }
    @media print { body { background: #fff; padding: 0; } .actions { display: none; } .sheet { border: none; } }
  </style>
</head>
<body>
  <div class="actions"><button type="button" onclick="window.print()">Print / save as PDF</button></div>
  <div class="sheet">${body}</div>
</body>
</html>`;
}

export type StatutoryEmployee = {
  forename: string;
  surname: string;
  nino: string;
  taxCode: string;
  payrollId: string;
  startDate: string;
  leaveDate?: string | null;
  niCategory?: string;
};

export type StatutoryEmployer = {
  name: string;
  payeRef: string;
  accountsOfficeRef?: string | null;
};

/**
 * Employee leaving statement (P45-style).
 * Employers still give leavers a P45 even though HMRC is notified via FPS.
 */
export function renderP45Html(opts: {
  employer: StatutoryEmployer;
  employee: StatutoryEmployee;
  taxYear: string;
  leaveDate: string;
  totals: YtdTotals;
  issuedAt?: string;
}) {
  const issued = opts.issuedAt ?? new Date().toISOString().slice(0, 10);
  const body = `
    <h1>P45 — Details of employee leaving work</h1>
    <p class="sub">Tax year ${esc(opts.taxYear)} · Issued ${esc(issued)} · HydraTax</p>

    <h2>Part 1 — Employer</h2>
    <table>
      <tr><th>Employer name</th><td>${esc(opts.employer.name)}</td></tr>
      <tr><th>PAYE reference</th><td>${esc(opts.employer.payeRef || "—")}</td></tr>
      <tr><th>Accounts office reference</th><td>${esc(opts.employer.accountsOfficeRef || "—")}</td></tr>
    </table>

    <h2>Part 2 — Employee</h2>
    <table>
      <tr><th>Name</th><td>${esc(opts.employee.forename)} ${esc(opts.employee.surname)}</td></tr>
      <tr><th>National Insurance number</th><td>${esc(opts.employee.nino)}</td></tr>
      <tr><th>Works / payroll number</th><td>${esc(opts.employee.payrollId)}</td></tr>
      <tr><th>Tax code at leaving</th><td>${esc(opts.employee.taxCode)}</td></tr>
      <tr><th>NI category</th><td>${esc(opts.employee.niCategory || "A")}</td></tr>
      <tr><th>Date employment started</th><td>${esc(opts.employee.startDate)}</td></tr>
      <tr><th>Date employment ended</th><td>${esc(opts.leaveDate)}</td></tr>
    </table>

    <h2>Part 3 — Pay and tax to date (this employment)</h2>
    <table>
      <tr><th>Total pay to date</th><td class="num">${gbp(opts.totals.taxablePence ?? opts.totals.grossPence)}</td></tr>
      <tr><th>Total tax to date</th><td class="num">${gbp(opts.totals.taxPence)}</td></tr>
      <tr><th>Employee NI to date</th><td class="num">${gbp(opts.totals.employeeNiPence)}</td></tr>
    </table>

    <p class="note">
      Give Parts 2 and 3 of this statement to the employee. They should give it to their next employer
      or to Jobcentre Plus / HMRC if they are not starting another job. Leaving details are also
      reported to HMRC on the Full Payment Submission (FPS). This document is generated by HydraTax
      for your records — verify figures against the final payslip before issue.
    </p>
  `;
  return documentShell(
    `P45 — ${opts.employee.forename} ${opts.employee.surname}`,
    body,
  );
}

/**
 * End-of-year certificate (P60-style) for an employee still on payroll at 5 April.
 */
export function renderP60Html(opts: {
  employer: StatutoryEmployer;
  employee: StatutoryEmployee;
  taxYear: string;
  /** Pay and tax in this employment only. */
  totals: YtdTotals;
  /** P45 figures from a previous employer in the same tax year, if any. */
  previousEmployment?: YtdTotals | null;
  issuedAt?: string;
}) {
  const issued = opts.issuedAt ?? new Date().toISOString().slice(0, 10);
  const prev = opts.previousEmployment;
  const prevBlock =
    prev &&
    ((prev.taxablePence ?? prev.grossPence) > 0 || prev.taxPence > 0)
      ? `
    <h2>Previous employment(s) this tax year</h2>
    <table>
      <tr><th>Total pay (previous)</th><td class="num">${gbp(prev.taxablePence ?? prev.grossPence)}</td></tr>
      <tr><th>Total tax deducted (previous)</th><td class="num">${gbp(prev.taxPence)}</td></tr>
      <tr><th>Employee NI (previous)</th><td class="num">${gbp(prev.employeeNiPence)}</td></tr>
    </table>`
      : "";
  const body = `
    <h1>P60 — End of Year Certificate</h1>
    <p class="sub">Tax year ${esc(opts.taxYear)} ending 5 April · Issued ${esc(issued)} · HydraTax</p>

    <h2>Employer</h2>
    <table>
      <tr><th>Employer name</th><td>${esc(opts.employer.name)}</td></tr>
      <tr><th>PAYE reference</th><td>${esc(opts.employer.payeRef || "—")}</td></tr>
    </table>

    <h2>Employee</h2>
    <table>
      <tr><th>Name</th><td>${esc(opts.employee.forename)} ${esc(opts.employee.surname)}</td></tr>
      <tr><th>National Insurance number</th><td>${esc(opts.employee.nino)}</td></tr>
      <tr><th>Works / payroll number</th><td>${esc(opts.employee.payrollId)}</td></tr>
      <tr><th>Final tax code</th><td>${esc(opts.employee.taxCode)}</td></tr>
      <tr><th>NI category</th><td>${esc(opts.employee.niCategory || "A")}</td></tr>
    </table>

    <h2>Pay and deductions in this employment</h2>
    <table>
      <tr><th>Total pay in this employment</th><td class="num">${gbp(opts.totals.taxablePence ?? opts.totals.grossPence)}</td></tr>
      <tr><th>Total tax deducted</th><td class="num">${gbp(opts.totals.taxPence)}</td></tr>
      <tr><th>Employee National Insurance contributions</th><td class="num">${gbp(opts.totals.employeeNiPence)}</td></tr>
    </table>
    ${prevBlock}

    <p class="note">
      Employers must give a P60 to every employee still on the payroll on 5 April, by 31 May.
      Keep a copy for your records. Figures should match the final FPS year-to-date totals for
      this employee. Generated by HydraTax — print or save as PDF for the employee.
    </p>
  `;
  return documentShell(
    `P60 — ${opts.employee.forename} ${opts.employee.surname} (${opts.taxYear})`,
    body,
  );
}
